fix svg file error using jakearchibald.github.io/svgomg
Previous error:
SyntaxError: /src/assets/car.svg: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.